class Path:
    HOME = "/"
    UPDATE = "/update"
    VERSION = "/version"
    INPUT = "/input"
    NEWFILE = "/newfile"
    LOGIN = "/login"
    ADD_USER = "/adduser"
    ALL_USERS = "/allusers"
    GET_USER = "/getuser"
